[[main]]
    identifier = "about"
    name = "About"
    title = "About me"
    url = "/about/"
    weight = 1

[[meta]]
    identifier = "categories"
    name = "Categories"
    weight = 1
[[meta]]
    identifier = "tags"
    name = "Tags"
    weight = 2


