baseURL = "https://hussainjk.github.io"
languageCode = "en"
defaultContentLanguage = "en-ca"
title = "Hussain Kadhem"
theme = "hugo-coder"

canonifyURLs = true
RelativeURLs=true
preserveTaxonomyNames = true
paginate = 10
paginatePath = "page"

[taxonomies]
    tags = "tags"
    categories = "categories"

[author]
    name = "Hussain Kadhem"
    email = "hussainmkj@gmail.com"

[services.rss]
    limit = 0

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

